org: frxnco
app: aws-python-spotifystats
service: aws-python-spotifystats

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  followers:
    handler: handler.followers
    events:
      - http:
          path: /followers
          method: get          
        
plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false